### ISSUE TITLE
❗️ Roadmap

### ISSUE THREAD

**Issue by jopemachine** [jopemachine/arvis#23]
# ❗️ Roadmap 

This issue shows future implementation plans.

Feel free to create any feature request comments.

## :rocket: To be implemented in short terms

- [x] ~~Support pdf display in quicklook~~ (0.8.12)
- [x] ~~Resolve https://github.com/jopemachine/arvis-core/issues/2~~ (0.10.0)

## :hammer: Long term goals

- [ ] Support `snippet` feature
- [ ] Support Universal action window
